# **Numerical Methods Assignment_1**


*   *Lakkoju Vikranth Ram* *ES23BTECH11024*
*   *Jayanth* *CO23BTECH11005*
*   *Kowshith* *ES23BTECH11015*
*   *Sathwik* *ES23BTECH11020*
*   *Deepak Joy* *ES23BTECH11014*



From python library we import NumPy function and create 2 arrays A and B respectivey and we will print array A

In [15]:
import pandas as pd
import numpy as np
df = pd.read_excel("input.xlsx")
df=df.dropna(axis=1,how='any')
df=df.dropna(axis=0,how='any')
A=df.iloc[:5].values
b1=df.iloc[5].values
b2=df.iloc[6].values
A,b1,b2

(array([[ 5,  2,  6,  4,  1],
        [ 2,  5,  9,  8,  7],
        [ 5,  4, 15,  0,  1],
        [ 4,  2,  3,  4,  6],
        [ 1,  2,  3,  4,  5]], dtype=int64),
 array([1, 2, 3, 4, 5], dtype=int64),
 array([ 2,  4,  8,  6, 10], dtype=int64))

# LU Decomposition

LU decomposition is a method for decomposing a matrix into a product of a lower triangular matrix (L) and an upper triangular matrix (U).

**Why LU Decomposition?**

* Solving systems of linear equations.
* Finding the inverse of a matrix.
* Computing the determinant of a matrix.


**How it Works:**


\begin{equation*}
L =
\begin{bmatrix}
1 & 0 & 0 \\
* & 1 & 0 \\
* & * & 1
\end{bmatrix}
\qquad
U =
\begin{bmatrix}
* & * & * \\
0 & * & * \\
0 & 0 & *
\end{bmatrix}
\end{equation*}


Where:

*  A is the original square matrix.
*  L is the lower triangular matrix.
*  U is the upper triangular matrix.

**Example:**
This code snippet demonstrates how to perform LU decomposition using the `scipy` library in Python.

**Note:** LU decomposition may require pivoting to ensure numerical stability.

In [ ]:
def LU_decomposition_with_pivoting(A):
    n = len(A)
    L = np.zeros((n, n))
    U = A.copy()
    P = np.eye(n)  # Permutation matrix
    
    for i in range(n):
        # Partial Pivoting: Find the maximum element in the current column
        max_row = np.argmax(abs(U[i:n, i])) + i
        if i != max_row:
            # Swap rows in U
            U[[i, max_row]] = U[[max_row, i]]
            # Swap rows in P
            P[[i, max_row]] = P[[max_row, i]]
            # Swap rows in L but only up to column i-1
            if i > 0:
                L[[i, max_row], :i] = L[[max_row, i], :i]
        
        # LU Decomposition
        for k in range(i+1, n):
            L[k, i] = U[k, i] / U[i, i]
            U[k, i:] -= L[k, i] * U[i, i:]
        
        L[i, i] = 1  # Diagonal elements of L are 1
    
    return L, U


(array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.4       ,  1.        ,  0.        ,  0.        ,  0.        ],
        [ 1.        ,  0.47619048,  1.        ,  0.        ,  0.        ],
        [ 0.8       ,  0.0952381 , -0.41463415,  1.        ,  0.        ],
        [ 0.2       ,  0.38095238, -0.12195122,  0.03571429,  1.        ]]),
 array([[ 5.        ,  2.        ,  6.        ,  4.        ,  1.        ],
        [ 0.        ,  4.2       ,  6.6       ,  6.4       ,  6.6       ],
        [ 0.        ,  0.        ,  5.85714286, -7.04761905, -3.14285714],
        [ 0.        ,  0.        ,  0.        , -2.73170732,  3.26829268],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  1.78571429]]))

To calculate the eigenvalues of the matrix $\mathbf{A}$ :

If the every diagonal element of the given matrix is non-zero then ,  

 we perform LU decomposition and iteratively update the matrix as follows:

1. Set up an initial matrix $\mathbf{A}$ and tolerance $\mathbf{tol}$.
2. Perform LU decomposition:
   \[
  $\mathbf{A = LU}$
   \]
3. Multiply $\mathbf{U}$ and $\mathbf{L}$ to update $\mathbf{A}$:
   \[
   $\mathbf{A = U \times L}$
   \]
4. Continue this process until $\mathbf{U}$ or $\mathbf{L}$ becomes close to the identity matrix $\mathbf{I}$. The eigenvalues will be the diagonal elements of $\mathbf{L}$ or $\mathbf{U}$.

The stopping condition is checked using the tolerance:
\[
$\mathbf{ |U - I| < tol \quad \text{or} \quad |L - I| < tol}$
\]



In [17]:
def eigen_values(A):
  n=len(A) 
  count = 0
  temp = A.copy()  # Create a copy of A to avoid modifying the original matrix
  while not np.all(np.diagonal(temp) != 0):
     temp = A + (count+1) * np.eye(n)
     count += 1
  eigen_values = np.zeros(n)
  while True:
      tolerance = 1e-9
      L,U=LU_decomposition(temp)
      temp = np.matmul(U, L)
      if np.all(abs(U-np.eye(n)) < tolerance):
        eigen_values = np.diag(L) - count
        break
      if np.all(abs(L-np.eye(n)) < tolerance):
        eigen_values = np.diag(U) - count
        break
  return eigen_values
eigen_values(A)

array([22.52689478,  8.94567003,  3.68271279, -1.6463513 ,  0.49107371])

If any of the diagonal elements of the matrix $\mathbf{A}$ is equal to $\mathbf{0}$, we use the shifting method. To handle this, we introduce a shift $\lambda$. The matrix $\mathbf{A}$ is modified by subtracting $\lambda$ times the identity matrix $\mathbf{I}$, where $\lambda$ is any eigenvalue of the given matrix:

\[
$A_{\lambda} = \mathbf{A} - \lambda \mathbf{I}$
\]

This shift modifies the matrix without changing its overall structure, but it ensures that none of the diagonal elements are zero. The eigenvalues of the new matrix are shifted by $\lambda$, so to obtain the eigenvalues of the original matrix, we add $\lambda$ to the eigenvalues obtained from $A_{\lambda}$.


We use the np.linalg.eigvals function from the Python library to check whether the eigenvalues we obtained are the true eigenvalues of the given matrix or not.

In [18]:
eigenvalues = np.linalg.eigvals(A)
eigenvalues

array([22.52689478, -1.6463513 ,  0.49107371,  3.68271279,  8.94567003])

**$\mathbf\large\text{det}(A) = \prod_{i=1}^{n} \lambda_i$**

The given code determines the determinant of the given matrix using it's eigen values,

determinant of the given matrix A is the produt of all of it's eigen values.



In [19]:
n=len(A)
eigen_values = np.linalg.eigvals(A)
determinant=1
for i in range(n):
  determinant*=eigen_values[i]

print(determinant)

-599.9999999999989


By using the  determinant of the matrix, we can determine the uniqueness of the system

 if  $\text{det}(A)\neq 0$  it indicates the uniqueness of the system of equations

 In the other case i.e., $\text{det}(A)=0$ then system of equations may have infinitely many solutions or no solution.

In [20]:
if determinant==0:
  print("The solutions of the system are not unique")
else:
  print("The solutions of the system are unique")

The solutions of the system are unique



$\Large \text{Condition Number} = \frac{\max(|\lambda|)}{\min(|\lambda|)}$

In [21]:
def condition_number(Matrix):
    eigen_values=np.linalg.eigvals(Matrix)
    condition_num= np.amax(abs(eigen_values))/np.amin(abs(eigen_values))
    return condition_num


This section of code calculates and compares the condition numbers of matrix A and a 5x5 Hilbert matrix. A Hilbert matrix is a square matrix where the elements are the unit fractions. Hilbert matrices are known to be ill-conditioned, meaning that they can be sensitive to small changes in input values, leading to large errors in the output. By comparing the condition numbers, you can assess the relative conditioning of matrix A to the Hilbert matrix.

In [22]:
from scipy.linalg import hilbert
Hilbert_matrix=hilbert(5)
print("condition number of the hilbert matrix is:")
print(condition_number(Hilbert_matrix))
print("condition number of the given matrix is:")
print(condition_number(A))
if (condition_number(A)>condition_number(Hilbert_matrix)):
  print(f"Condition number of the given matrix is greater than condition number of the hilbert matrix")
if (condition_number(A)<condition_number(Hilbert_matrix)):
  print(f"Condition number of the hilbert matrix is greater than condition number of the given matrix")
else:
  print(f"Condition number of the given matrix is equal to condition number of the hilbert matrix")

condition number of the hilbert matrix is:
476607.2502427483
condition number of the given matrix is:
45.87273627139868
Condition number of the hilbert matrix is greater than condition number of the given matrix


Here we are finding the coefficients of characteristic polynomial equation for matrix $\text{A}$
where the characteristic polynomial equation is of the form: \\
$a_0\lambda^5+a_1\lambda^4+a_2\lambda^3+a_3\lambda^2+a_4\lambda+a_5$ \\
The roots of the characteristic polynomial equation are the eigenvalues of matrix A. This code calculates the polynomial coefficients in the order $a_0, a_1, a_2, a_3, a_4, a_5$.

In [23]:
from numpy.polynomial import polynomial as P

# Assuming eigen_values is a numpy array containing the eigenvalues
polynomial = np.round (P.polyfromroots(eigen_values))
polynomial = np.flip(polynomial)
np.set_printoptions(suppress=True)
print((polynomial[0:len(polynomial)]))
for i, coeff in enumerate(polynomial):
  print(f"{coeff}x^{len(polynomial)-i-1} + ", end="")
print(0)

[    1.   -34.   276.  -347. -1114.   600.]
1.0x^5 + -34.0x^4 + 276.0x^3 + -347.0x^2 + -1114.0x^1 + 600.0x^0 + 0


In [24]:
print(np.roots(polynomial))

[22.52689478  8.94567003  3.68271279 -1.6463513   0.49107371]


In [25]:
A_INV=np.linalg.inv(A)
print(A_INV)

[[ 0.02        0.08       -0.02        0.34       -0.52      ]
 [-0.86        1.56       -0.14        1.38       -3.64      ]
 [ 0.22666667 -0.42666667  0.10666667 -0.48        1.10666667]
 [ 0.33       -0.18       -0.08       -0.39        0.67      ]
 [-0.06       -0.24        0.06       -0.02        0.56      ]]


This code calculates the absolute maximum and minimum eigenvalues of matrix A using the power method.

The power method is an iterative algorithm that finds the dominant eigenvalue (largest eigenvalue in absolute value) and its corresponding eigenvector. To find the absolute minimum eigenvalue, the power method is applied to the inverse of A. The reciprocal of the absolute maximum eigenvalue of the inverse matrix is then the absolute minimum eigenvalue of the original matrix.

In [26]:
def eigen_vector_power(matrix)-> float:
  eigen_vector = np.array((1,0,0,0,0))
  temp = np.array((100,0,0,0,0))
  tol=0.00001
  while True :
      eigen_vector = np.matmul(matrix,eigen_vector)/np.amax(eigen_vector)
      if (abs(np.amax(temp)-np.amax(eigen_vector))<tol and abs(np.all(temp-eigen_vector))<tol):
        return (np.amax(eigen_vector))
        break
      temp=np.amax(eigen_vector)

print(f"The maximum eigen value using power method :{eigen_vector_power(A)}")
print(f"Minimum Eigen value of the matrix using inverse power method :{1/eigen_vector_power(A_INV)}")
print(np.amax(eigen_values))
print(np.amin(abs(eigen_values)))

The maximum eigen value using power method :22.52689477659869
Minimum Eigen value of the matrix using inverse power method :0.4910737097373484
22.52689477659868
0.4910737097373465


This statement suggests cross-referencing the results of the power method with the eigenvalues obtained through LU decomposition. It serves as a verification step to ensure the accuracy and consistency of the calculated eigenvalues

This code calculates the inverse of matrix A using the Gauss-Jordan elimination method. The Gauss-Jordan method is a standard algorithm for finding the inverse of a matrix by transforming the augmented matrix (A|I), where I is the identity matrix, into reduced row-echelon form (I|A^-1). The resulting matrix on the right side of the augmented matrix is the inverse of the original matrix.

In [27]:
import numpy as np

def gauss_jordan_inverse(a):
    a = np.array(a, float)
    n = len(a)
    tol = 1e-8
    # Augmenting with identity matrix
    inverse = np.identity(n)

    # Main loop
    for k in range(n):
        # Partial pivoting
        if np.fabs(a[k, k]) < tol:
            for i in range(k + 1, n):
                if np.fabs(a[i, k]) > np.fabs(a[k, k]):
                    # Swap rows in both matrix 'a' and 'inverse'
                    a[[k, i]] = a[[i, k]]
                    inverse[[k, i]] = inverse[[i, k]]
                    break

        # Divide the pivot row by the diagonal element
        div = a[k, k]
        a[k, :] /= div
        inverse[k, :] /= div

        # Elimination process
        for i in range(n):
            if i == k:
                continue
            factor = a[i, k]
            a[i, :] -= factor * a[k, :]
            inverse[i, :] -= factor * inverse[k, :]

    return inverse
import numpy as np
A=np.array([[5,2,6,4,1],[2,5,9,8,7],[5,4,15,0,1],[4,2,3,4,6],[1,2,3,4,5]])
B=np.array([1,2,3,4,5])
A
print(gauss_jordan_inverse(A))


[[ 0.02        0.08       -0.02        0.34       -0.52      ]
 [-0.86        1.56       -0.14        1.38       -3.64      ]
 [ 0.22666667 -0.42666667  0.10666667 -0.48        1.10666667]
 [ 0.33       -0.18       -0.08       -0.39        0.67      ]
 [-0.06       -0.24        0.06       -0.02        0.56      ]]


Here we are finding the solution for system of equations Ax=b by using LU Decomposition by changing the b-vector for the same given matrix.

In [28]:
def forward_substitution(L, b):
    n = len(b)
    y = np.zeros(n)
    for i in range(n):
        y[i] = b[i] - sum(L[i][j] * y[j] for j in range(i))
    return y

def backward_substitution(U, y):
    n = len(y)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - sum(U[i][j] * x[j] for j in range(i+1, n))) / U[i][i]
    return x

def solve_system(A, b):
    L, U = LU_decomposition(A)
    y = forward_substitution(L, b)
    x = backward_substitution(U, y)
    return x

solve_system(A,b1)
solve_system(A,b2)

array([ -2.96      , -24.72      ,   7.78666667,   3.66      ,
         4.88      ])